// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdytvvkmdfmglrdklhxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkeXR2dmttZGZtZ2xyZGtsaHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMzM0MzMsImV4cCI6MjA1MzcwOTQzM30.vvmmq3yPVCirx2VkblhCjkGDTJUU9Tx9CIo5YtPCci0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);